-- AI Video Director — initial SaaS data model
-- Apply to PostgreSQL 15+ with a migration runner. UUIDs are generated by the application.

CREATE TYPE membership_role AS ENUM ('owner', 'editor', 'viewer');
CREATE TYPE project_status AS ENUM ('draft', 'planning', 'in_review', 'approved', 'production', 'archived');
CREATE TYPE plan_status AS ENUM ('draft', 'in_review', 'approved', 'superseded');
CREATE TYPE clip_status AS ENUM ('planned', 'generating', 'generated', 'under_review', 'approved', 'rejected', 'revision_required');
CREATE TYPE job_status AS ENUM ('queued', 'running', 'succeeded', 'failed', 'cancelled');

CREATE TABLE users (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT,
  -- scrypt output encoded as "saltHex:hashHex"; see apps/web/lib/password.js.
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE workspaces (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- token_hash (sha256 of the bearer token in the session cookie) so a database read alone
-- doesn't hand over a valid session, mirroring how passwords are never stored in the clear.
CREATE TABLE sessions (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX sessions_token_hash_idx ON sessions (token_hash);

CREATE TABLE memberships (
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role membership_role NOT NULL DEFAULT 'viewer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id)
);

CREATE TABLE projects (
  id UUID PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  status project_status NOT NULL DEFAULT 'draft',
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived_at TIMESTAMPTZ
);
CREATE INDEX projects_workspace_updated_idx ON projects (workspace_id, updated_at DESC);

CREATE TABLE project_briefs (
  project_id UUID PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
  premise TEXT NOT NULL,
  target_audience TEXT NOT NULL,
  runtime_seconds INTEGER NOT NULL CHECK (runtime_seconds BETWEEN 5 AND 14400),
  aspect_ratio TEXT NOT NULL CHECK (aspect_ratio IN ('16:9', '9:16', '1:1', 'custom')),
  visual_direction TEXT,
  constraints JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- overview/creative_direction/cinematic_bible/continuity_map/project_state are document-shaped
-- planning output (see @avid/domain ProductionPlan) with no independent relational identity.
CREATE TABLE production_plans (
  id UUID PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  revision INTEGER NOT NULL CHECK (revision > 0),
  status plan_status NOT NULL DEFAULT 'draft',
  overview JSONB NOT NULL,
  creative_direction JSONB NOT NULL,
  screenplay JSONB NOT NULL,
  cinematic_bible JSONB NOT NULL,
  continuity_map JSONB NOT NULL DEFAULT '{"transitions": []}'::jsonb,
  project_state JSONB NOT NULL,
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  UNIQUE (project_id, revision)
);
CREATE INDEX production_plans_project_status_idx ON production_plans (project_id, status);

CREATE TABLE characters (
  id UUID PRIMARY KEY,
  plan_id UUID NOT NULL REFERENCES production_plans(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  apparent_age TEXT NOT NULL,
  build TEXT NOT NULL,
  face TEXT NOT NULL,
  hair TEXT NOT NULL,
  outfit TEXT NOT NULL,
  accessories JSONB NOT NULL DEFAULT '[]'::jsonb,
  physical_condition TEXT NOT NULL,
  emotional_state TEXT NOT NULL,
  arc TEXT NOT NULL,
  identity_lock_prompt TEXT,
  reference_asset_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE locations (
  id UUID PRIMARY KEY,
  plan_id UUID NOT NULL REFERENCES production_plans(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  architecture TEXT NOT NULL,
  materials TEXT NOT NULL,
  climate TEXT NOT NULL,
  time_of_day TEXT NOT NULL,
  lighting TEXT NOT NULL,
  damage_state TEXT NOT NULL,
  atmosphere TEXT NOT NULL,
  identity_lock_prompt TEXT,
  reference_asset_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sequences (
  id UUID PRIMARY KEY,
  plan_id UUID NOT NULL REFERENCES production_plans(id) ON DELETE CASCADE,
  sequence_number INTEGER NOT NULL CHECK (sequence_number > 0),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (plan_id, sequence_number)
);

CREATE TABLE scenes (
  id UUID PRIMARY KEY,
  sequence_id UUID NOT NULL REFERENCES sequences(id) ON DELETE CASCADE,
  scene_number INTEGER NOT NULL CHECK (scene_number > 0),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  duration_seconds INTEGER NOT NULL CHECK (duration_seconds > 0),
  status plan_status NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (sequence_id, scene_number)
);

-- character_ids is a JSONB array of character UUIDs: a clip's cast is metadata, not an
-- independently queried relation, so a join table is unneeded for the MVP.
CREATE TABLE clips (
  id UUID PRIMARY KEY,
  scene_id UUID NOT NULL REFERENCES scenes(id) ON DELETE CASCADE,
  clip_number INTEGER NOT NULL CHECK (clip_number > 0),
  narrative_purpose TEXT NOT NULL,
  action TEXT NOT NULL,
  character_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  camera_shot TEXT NOT NULL,
  camera_movement TEXT NOT NULL,
  lighting TEXT NOT NULL,
  starting_state JSONB NOT NULL,
  ending_state JSONB NOT NULL,
  duration_seconds INTEGER NOT NULL CHECK (duration_seconds > 0),
  status clip_status NOT NULL DEFAULT 'planned',
  prompt JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (scene_id, clip_number)
);

CREATE TABLE assets (
  id UUID PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  clip_id UUID REFERENCES clips(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('reference_image', 'video_clip', 'audio', 'frame', 'document')),
  storage_key TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX assets_project_idx ON assets (project_id, created_at DESC);

CREATE TABLE jobs (
  id UUID PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  clip_id UUID REFERENCES clips(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('planning', 'reference_generation', 'media_generation', 'assembly')),
  status job_status NOT NULL DEFAULT 'queued',
  idempotency_key TEXT NOT NULL UNIQUE,
  provider_name TEXT,
  provider_job_id TEXT,
  input JSONB NOT NULL DEFAULT '{}'::jsonb,
  output JSONB,
  error_message TEXT,
  attempts INTEGER NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX jobs_project_status_idx ON jobs (project_id, status, created_at DESC);

CREATE TABLE activity_events (
  id UUID PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX activity_events_project_idx ON activity_events (project_id, created_at DESC);
